import { columns } from "./_components/columns"
import type { Blog } from "./_components/columns"
import { DataTable } from "./_components/data-table"

async function getData(): Promise<Blog[]> {
  const blogs: Blog[] = [
    {
      id: "1",
      titel: "Waarom kiezen voor een groendak?",
      status: "gepubliceerd",
      categorie: "Groendaken",
      tags: ["sedum", "duurzaamheid"],
      auteur: "Mark de Vries",
      datum: "Laatst gewijzigd op 4 januari om 08:45",
    },
    {
      id: "2",
      titel: "5 voordelen van zonnepanelen",
      status: "concept",
      categorie: "Zonnepanelen",
      tags: ["energie", "besparing"],
      auteur: "Pien Strik",
      datum: "Laatst gewijzigd op 8 januari om 08:45",
    },
    {
      id: "3",
      titel: "Hoe werkt een laadpaal thuis?",
      status: "ingepland",
      categorie: "Laadpalen",
      tags: ["elektrisch rijden", "woning"],
      auteur: "Angela Jansen",
      datum: "Laatst gewijzigd op 12 januari om 08:45",
    },
    {
      id: "4",
      titel: "Duurzaam wonen voor beginners",
      status: "gepubliceerd",
      categorie: "Duurzaam wonen",
      tags: ["woning", "tips"],
      auteur: "Mark de Vries",
      datum: "Laatst gewijzigd op 15 januari om 08:45",
    },
    {
      id: "5",
      titel: "Sedumdaken en wateropvang",
      status: "concept",
      categorie: "Groendaken",
      tags: ["regenwater", "sedum"],
      auteur: "Pien Strik",
      datum: "Laatst gewijzigd op 18 januari om 08:45",
    },
    {
      id: "6",
      titel: "Waarom elektrisch rijden populairder wordt",
      status: "gepubliceerd",
      categorie: "Laadpalen",
      tags: ["mobiliteit", "duurzaam"],
      auteur: "Angela Jansen",
      datum: "Laatst gewijzigd op 20 januari om 08:45",
    },
    {
      id: "7",
      titel: "De impact van groene energie",
      status: "ingepland",
      categorie: "Energie",
      tags: ["groene energie", "toekomst"],
      auteur: "Mark de Vries",
      datum: "Laatst gewijzigd op 23 januari om 08:45",
    },
    {
      id: "8",
      titel: "Tips voor een energiezuinig huis",
      status: "gepubliceerd",
      categorie: "Duurzaam wonen",
      tags: ["energie", "woning"],
      auteur: "Pien Strik",
      datum: "Laatst gewijzigd op 25 januari om 08:45",
    },
    {
      id: "9",
      titel: "Hoe onderhoud je een groendak?",
      status: "concept",
      categorie: "Groendaken",
      tags: ["onderhoud", "sedum"],
      auteur: "Angela Jansen",
      datum: "Laatst gewijzigd op 28 januari om 08:45",
    },
    {
      id: "10",
      titel: "Subsidies voor zonnepanelen in 2026",
      status: "gepubliceerd",
      categorie: "Zonnepanelen",
      tags: ["subsidie", "energie"],
      auteur: "Mark de Vries",
      datum: "Laatst gewijzigd op 1 februari om 08:45",
    },
    {
      id: "11",
      titel: "De toekomst van duurzame steden",
      status: "ingepland",
      categorie: "Duurzaamheid",
      tags: ["stad", "innovatie"],
      auteur: "Pien Strik",
      datum: "Laatst gewijzigd op 3 februari om 08:45",
    },
    {
      id: "12",
      titel: "Waarom isolatie belangrijk is",
      status: "concept",
      categorie: "Duurzaam wonen",
      tags: ["isolatie", "energie"],
      auteur: "Angela Jansen",
      datum: "Laatst gewijzigd op 6 februari om 08:45",
    },
    {
      id: "13",
      titel: "Groene trends van dit jaar",
      status: "gepubliceerd",
      categorie: "Duurzaamheid",
      tags: ["trends", "groen"],
      auteur: "Mark de Vries",
      datum: "Laatst gewijzigd op 8 februari om 08:45",
    },
    {
      id: "14",
      titel: "De voordelen van warmtepompen",
      status: "ingepland",
      categorie: "Energie",
      tags: ["warmtepomp", "woning"],
      auteur: "Pien Strik",
      datum: "Laatst gewijzigd op 10 februari om 08:45",
    },
    {
      id: "15",
      titel: "Meer biodiversiteit met groendaken",
      status: "gepubliceerd",
      categorie: "Groendaken",
      tags: ["natuur", "biodiversiteit"],
      auteur: "Angela Jansen",
      datum: "Laatst gewijzigd op 14 februari om 08:45",
    },
    {
      id: "16",
      titel: "Zo bespaar je stroom in huis",
      status: "concept",
      categorie: "Energie",
      tags: ["besparing", "tips"],
      auteur: "Mark de Vries",
      datum: "Laatst gewijzigd op 18 februari om 08:45",
    },
    {
      id: "17",
      titel: "Wat kost een laadpaal installeren?",
      status: "gepubliceerd",
      categorie: "Laadpalen",
      tags: ["kosten", "installatie"],
      auteur: "Pien Strik",
      datum: "Laatst gewijzigd op 20 februari om 08:45",
    },
    {
      id: "18",
      titel: "Waarom duurzaam bouwen groeit",
      status: "ingepland",
      categorie: "Duurzaamheid",
      tags: ["bouwen", "innovatie"],
      auteur: "Angela Jansen",
      datum: "Laatst gewijzigd op 22 februari om 08:45",
    },
    {
      id: "19",
      titel: "Zonnepanelen in de winter",
      status: "concept",
      categorie: "Zonnepanelen",
      tags: ["winter", "energie"],
      auteur: "Mark de Vries",
      datum: "Laatst gewijzigd op 25 februari om 08:45",
    },
    {
      id: "20",
      titel: "Duurzame keuzes voor bedrijven",
      status: "gepubliceerd",
      categorie: "Duurzaamheid",
      tags: ["bedrijven", "groen"],
      auteur: "Pien Strik",
      datum: "Laatst gewijzigd op 28 februari om 08:45",
    },
    {
      id: "021",
      titel: "De voordelen van regenwateropvang",
      status: "gepubliceerd",
      categorie: "Duurzaam wonen",
      tags: ["regenwater", "milieu"],
      auteur: "Mark de Vries",
      datum: "Laatst gewijzigd op 1 maart om 08:45",
    },
    {
      id: "022",
      titel: "Hoe werkt een thuisbatterij?",
      status: "concept",
      categorie: "Energie",
      tags: ["batterij", "opslag"],
      auteur: "Pien Strik",
      datum: "Laatst gewijzigd op 3 maart om 08:45",
    },
    {
      id: "023",
      titel: "Groene tuinen voor meer biodiversiteit",
      status: "ingepland",
      categorie: "Duurzaamheid",
      tags: ["tuin", "natuur"],
      auteur: "Angela Jansen",
      datum: "Laatst gewijzigd op 5 maart om 08:45",
    },
    {
      id: "024",
      titel: "Waarom bedrijven investeren in duurzaamheid",
      status: "gepubliceerd",
      categorie: "Duurzaamheid",
      tags: ["bedrijven", "groei"],
      auteur: "Mark de Vries",
      datum: "Laatst gewijzigd op 7 maart om 08:45",
    },
    {
      id: "025",
      titel: "Wat kost een warmtepomp?",
      status: "concept",
      categorie: "Energie",
      tags: ["warmtepomp", "kosten"],
      auteur: "Pien Strik",
      datum: "Laatst gewijzigd op 9 maart om 08:45",
    },
    {
      id: "026",
      titel: "De toekomst van elektrisch rijden",
      status: "gepubliceerd",
      categorie: "Laadpalen",
      tags: ["elektrisch", "mobiliteit"],
      auteur: "Angela Jansen",
      datum: "Laatst gewijzigd op 11 maart om 08:45",
    },
    {
      id: "027",
      titel: "Groendaken in stedelijke gebieden",
      status: "ingepland",
      categorie: "Groendaken",
      tags: ["stad", "sedum"],
      auteur: "Mark de Vries",
      datum: "Laatst gewijzigd op 13 maart om 08:45",
    },
    {
      id: "028",
      titel: "Hoe verlaag je je energierekening?",
      status: "gepubliceerd",
      categorie: "Energie",
      tags: ["besparing", "woning"],
      auteur: "Pien Strik",
      datum: "Laatst gewijzigd op 15 maart om 08:45",
    },
    {
      id: "029",
      titel: "Duurzame oplossingen voor kantoren",
      status: "concept",
      categorie: "Duurzaamheid",
      tags: ["kantoor", "groen"],
      auteur: "Angela Jansen",
      datum: "Laatst gewijzigd op 17 maart om 08:45",
    },
    {
      id: "030",
      titel: "Waarom kiezen voor zonne-energie?",
      status: "gepubliceerd",
      categorie: "Zonnepanelen",
      tags: ["zon", "energie"],
      auteur: "Mark de Vries",
      datum: "Laatst gewijzigd op 19 maart om 08:45",
    },
    {
      id: "031",
      titel: "Slimme energiebesparing in huis",
      status: "ingepland",
      categorie: "Duurzaam wonen",
      tags: ["smart home", "energie"],
      auteur: "Pien Strik",
      datum: "Laatst gewijzigd op 21 maart om 08:45",
    },
    {
      id: "032",
      titel: "De groei van groene mobiliteit",
      status: "concept",
      categorie: "Laadpalen",
      tags: ["mobiliteit", "toekomst"],
      auteur: "Angela Jansen",
      datum: "Laatst gewijzigd op 22 maart om 08:45",
    },
    {
      id: "033",
      titel: "Hoe onderhoud je zonnepanelen?",
      status: "gepubliceerd",
      categorie: "Zonnepanelen",
      tags: ["onderhoud", "panelen"],
      auteur: "Mark de Vries",
      datum: "Laatst gewijzigd op 23 maart om 08:45",
    },
    {
      id: "034",
      titel: "Duurzaam leven stap voor stap",
      status: "ingepland",
      categorie: "Duurzaam wonen",
      tags: ["tips", "duurzaam"],
      auteur: "Pien Strik",
      datum: "Laatst gewijzigd op 24 maart om 08:45",
    },
    {
      id: "035",
      titel: "Waarom sedumdaken populair zijn",
      status: "gepubliceerd",
      categorie: "Groendaken",
      tags: ["sedum", "dak"],
      auteur: "Angela Jansen",
      datum: "Laatst gewijzigd op 25 maart om 08:45",
    },
    {
      id: "036",
      titel: "Groene energie voor bedrijven",
      status: "concept",
      categorie: "Energie",
      tags: ["bedrijven", "energie"],
      auteur: "Mark de Vries",
      datum: "Laatst gewijzigd op 26 maart om 08:45",
    },
    {
      id: "037",
      titel: "De voordelen van isolatie",
      status: "gepubliceerd",
      categorie: "Duurzaam wonen",
      tags: ["isolatie", "woning"],
      auteur: "Pien Strik",
      datum: "Laatst gewijzigd op 27 maart om 08:45",
    },
    {
      id: "038",
      titel: "Hoe werkt slim laden?",
      status: "ingepland",
      categorie: "Laadpalen",
      tags: ["slim laden", "auto"],
      auteur: "Angela Jansen",
      datum: "Laatst gewijzigd op 28 maart om 08:45",
    },
    {
      id: "039",
      titel: "Wat zijn circulaire materialen?",
      status: "gepubliceerd",
      categorie: "Duurzaamheid",
      tags: ["circulair", "materialen"],
      auteur: "Mark de Vries",
      datum: "Laatst gewijzigd op 29 maart om 08:45",
    },
    {
      id: "040",
      titel: "Meer groen rondom woningen",
      status: "concept",
      categorie: "Groendaken",
      tags: ["groen", "omgeving"],
      auteur: "Pien Strik",
      datum: "Laatst gewijzigd op 30 maart om 08:45",
    },
    {
      id: "041",
      titel: "De impact van duurzame keuzes",
      status: "gepubliceerd",
      categorie: "Duurzaamheid",
      tags: ["impact", "milieu"],
      auteur: "Angela Jansen",
      datum: "Laatst gewijzigd op 1 april om 08:45",
    },
    {
      id: "042",
      titel: "Waarom laadpalen belangrijk zijn",
      status: "ingepland",
      categorie: "Laadpalen",
      tags: ["laden", "duurzaam"],
      auteur: "Mark de Vries",
      datum: "Laatst gewijzigd op 3 april om 08:45",
    },
    {
      id: "043",
      titel: "Hoe werkt energieneutraal wonen?",
      status: "concept",
      categorie: "Duurzaam wonen",
      tags: ["energieneutraal", "woning"],
      auteur: "Pien Strik",
      datum: "Laatst gewijzigd op 5 april om 08:45",
    },
    {
      id: "044",
      titel: "Innovaties in zonne-energie",
      status: "gepubliceerd",
      categorie: "Zonnepanelen",
      tags: ["innovatie", "zon"],
      auteur: "Angela Jansen",
      datum: "Laatst gewijzigd op 7 april om 08:45",
    },
    {
      id: "045",
      titel: "Duurzame keuzes voor nieuwbouw",
      status: "ingepland",
      categorie: "Duurzaam wonen",
      tags: ["nieuwbouw", "groen"],
      auteur: "Mark de Vries",
      datum: "Laatst gewijzigd op 9 april om 08:45",
    },
    {
      id: "046",
      titel: "Groene daken en verkoeling",
      status: "gepubliceerd",
      categorie: "Groendaken",
      tags: ["verkoeling", "dak"],
      auteur: "Pien Strik",
      datum: "Laatst gewijzigd op 11 april om 08:45",
    },
    {
      id: "047",
      titel: "Waarom duurzaam ondernemen groeit",
      status: "concept",
      categorie: "Duurzaamheid",
      tags: ["ondernemen", "toekomst"],
      auteur: "Angela Jansen",
      datum: "Laatst gewijzigd op 13 april om 08:45",
    },
    {
      id: "048",
      titel: "Tips voor een lagere CO2-uitstoot",
      status: "gepubliceerd",
      categorie: "Energie",
      tags: ["co2", "milieu"],
      auteur: "Mark de Vries",
      datum: "Laatst gewijzigd op 15 april om 08:45",
    },
    {
      id: "049",
      titel: "Hoe kies je de juiste laadpaal?",
      status: "ingepland",
      categorie: "Laadpalen",
      tags: ["advies", "auto"],
      auteur: "Pien Strik",
      datum: "Laatst gewijzigd op 17 april om 08:45",
    },
    {
      id: "050",
      titel: "De toekomst van duurzaam wonen",
      status: "gepubliceerd",
      categorie: "Duurzaam wonen",
      tags: ["toekomst", "woning"],
      auteur: "Angela Jansen",
      datum: "Laatst gewijzigd op 19 april om 08:45",
    },
  ]

  return blogs.reverse()
}

export default async function DemoPage() {
  const data = await getData()

  return (
    <div className="container mx-auto w-full max-w-10xl px-4 py-10 lg:px-8">
      <h1 className="text-3xl font-bold text-[#52525C]">Blogs</h1>
      <DataTable columns={columns} data={data} />
    </div>
  )
}
